### ISSUE TITLE
How do I use my own data set

### ISSUE THREAD

**Issue by yayaYsmile** [christinecui/IRGNNH#1]
Hello, I wonder if I can use my own data set for image retrieval? How to implement it? Also, I would like to know how the.pkl file was obtained.

Thank you for your reply

**Comment by christinecui** [comment]
Of course, you can make your dataset.
The general steps are:
(1) Prepare raw images (such as jpg images)
(2) Use a deep neural network to extract features (such as VGG16)
(3) Save variables such as image features and labels in pkl format
